VisionSystemsInc/terra

terra/compute/virtualenv.py

Log a warning if the virtualenv command is not found in the virtualenv dir, just in case the user mistyped the compute.virtualenv_dir setting.

Virtualenv Warning

---

terra/core/settings.py
terra/tests/test_utils_workflow.py
terra/utils/workflow.py

Temporarily sets overwrite to True when resuming a broken stage. Lead to the discovery and fix of a bug in settings.py, where nested settings context managers weren't supported. A unit test checking nested CMs should be created.

Temporary Overwrite of Broken Stages

---

terra/compute/virtualenv.py

fix virtualenv_dir warning message - `is_subdir` returns a tuple, a warning should be thrown only if the first returned element is `False`.

fix virtualenv_dir warning message 

---

.circleci/config.yml
docs/conf.py
terra/compute/utils.py
terra/core/settings.py
terra/core/signals.py
terra/core/utils.py

Add `intersphinx_mapping` to sphinx docs `conf.py`, allowing documentation to appropriately cross-reference against other documentation. Note this drastically reduces the necessary `nitpick_ignore` list and should make future documentation have fewer errors.
Add `--keep-going` to circleci `compile_docs` to make visible all sphinx errors (not just the first one).

sphinx cross-referencing

---

terra/compute/base.py
terra/compute/container.py
terra/compute/virtualenv.py

New flag `local_must_exist` for service `add_volume()` to let users enforce local file/folder existence. 
Note that all `add_volume` functions now use `BaseService._validate_volume()` to validate the local and/or remote inputs, which now raises exceptions on invalid inputs.

local_must_exist

---

terra/compute/base.py
terra/compute/container.py
terra/compute/utils.py
terra/compute/virtualenv.py
terra/core/settings.py
terra/executor/dummy.py
terra/task.py

- Now executor settings are auto translated from runner to exectutor,
instead of from master controller to executor. This clears the path to
more consistent behavior when it comes to passing in arguments.
- Task args and kwargs that match the same suffix patterns settings so,
will now be auto translated from runner to task. This should make for
a more seemless transaction to task, as long as the variable names are
right.
- Executor and compute both have a volume map store in the settings now.

Auto translate arguments to task functions

---

terra.env
terra/compute/container.py
terra/compute/docker.py
terra/compute/singularity.py
terra/compute/virtualenv.py
terra/executor/celery/__init__.py
terra/task.py

- Temporary directors have a meaningful suffix
- TERRA_KEEP_TEMP_DIR added for debuging
- TERRA_CELERY_MAIN_NAME is automatic now
- config.json.orig removed, as no longer needed
- Fixed a duplicate volume_map bug
Signed-off-by: Andy Neff <andy@visionsystemsinc.com>

Return values in celery get volume translations

---

terra.env

Disallow certain characters in the randomly generated passwords used for redis/celery: `;` (for an unknown redis/celery parsing reason), `:` or `@` (for redis url parsing reasons)

update password mask

---

Justfile
docker-compose-main.yml
terra/compute/base.py
terra/compute/utils.py
terra/core/settings.py
terra/executor/base.py
terra/executor/celery/__init__.py
terra/executor/celery/__main__.py
terra/executor/celery/executor.py
terra/executor/process.py
terra/executor/thread.py
terra/executor/utils.py
terra/logger.py
terra/task.py

sgrichar celery alpha

---

Justfile
terra/core/exceptions.py
terra/core/settings.py

Create graceful errors for Config JSON parsing errors and config file not found.
Some error, we know what is wrong, and a stack trace is not necessary. Furthermore, they are user based errors (Like bad json filename or json malformed) and a stack trace is not needed for the user.
Now, instead of raising an exception when we know the error, and having a nasty backtrace printed out, we can `raise SystemExit(terra.core.exceptions.handledExitCode` and now Python and Just will not print out a stack. A `logger.critical` should precede the `SystemExit`, or else the user will not see what is wrong.

Added error handling for common terra issues

---

Justfile
terra/core/exceptions.py
terra/core/settings.py
terra/tests/utils.py

The code for using `settings.terra.config_file` to determine `settings.processing_dir` was not working due to a chicken-egg issue.
- Calls configure
- Send signal
- Logger receives signal, and start setting up logger
- Needs to know where to put log files, so check `settings.processing_dir`
- `settings.processing_dir` looks for `setttings.terra.config_file`, doesn't see it yet
- Returns to _setup
- Then set `settings.terra.config_file`, but it's too late
The solution was essentially to use a global/singleton variable 😞 to get around this issue.

Fix processing dir default

---

terra/compute/container.py
terra/core/settings.py
terra/logger.py

Save settings dump files to `settings_dump_dir`, defaulting to the directory `processing_dir\settings_dump`.  This should eliminate the need for apps to mount the processing directory.

settings_dump_dir

---

terra/compute/utils.py
terra/tests/test_compute_utils.py

Use pathlib for `compute.utils.translate_settings_paths` for all flavors of `container_platform`.  Additionally break path translation steps into separate functions for more unit tests.
This addresses a bug where a user has the following setup, where the output directory starts with the same string as the input directory (though output and input are separate folders).  This is a valid configuration and should be handled.
- Input path = `/path/to/data`
- Output path = `/path/to/data_output`
Consider the following configuration:
```
{
"image_dir": "/path/to/data",
"service_dir": "/path/to/data_output/service",
}
```
And the following volume_map:
```
[
["/path/to/data_output/service", "/dem/service"],
["/path/to/data", "/dem/images"]
]
```
A volume_map using string comparison produces the …

pathlib for volume_map translation

---

terra.env
terra/core/settings.py

dynamic settings `logging_hostname` and environment variable `TERRA_RESOLVE_HOSTNAME` that attempts to resolve the IP of the default route on the host as per https://stackoverflow.com/a/28950776.  This optional setting can overcome situations where the logging module fails to resolve the hostname, resulting in missing service & task logs from `terra_log`
By default, we maintain current operation of `hostname == platform.node()`.  User must explicitly enable resolution by setting `TERRA_RESOLVE_HOSTNAME=1`.

dynamic logging_hostname

---

Justfile

Update Justfile for file name change (`get-pipenv` -> `30_get-pipenv`) in `vsi_common/docker/recipes` introduced by https://github.com/VisionSystemsInc/docker_recipes/pull/14

Justfile: get-pipenv -> 30_get-pipenv

---

terra/compute/base.py
terra/core/settings.py

Add `settings.logging.server.listen_address`, allowing the logging server listen address to be overridden.  For example, the logging server may be bound to the more permissive `0.0.0.0`, while logging clients transmit to the actual host IP.

logging listen address

---

terra/task.py

Fixes the issue in windows when running a task can cause
```
Traceback (most recent call last):
File "...\Python37_64\Lib\concurrent\futures\process.py", line 239, in _process_worker
r = call_item.fn(*call_item.args, **call_item.kwargs)
File "...\terra\terra\task.py", line 140, in __call__
settings.terra.zone = original_zone
UnboundLocalError: local variable 'original_zone' referenced before assignment
```

Patch for Issue #55

---

.circleci/config.yml

update ci_load to use latest from vsi_common.  ci_load push only on master branch from main repo (no forks).  Additional circleci comments for clarity.

update for ci_load

---

terra/core/settings.py

Add the default setting executor.num_workers, initialize it with the number of cpu cores.

Default executor.num_workers

---

terra/core/settings.py

workflow.py references settings.service_start and settings.service_end in the pipeline logic. They need to have default values, or else it will crash if the Terra App doesn't define service_start and service_end in its own defaults.

Default service start / end

---

terra/core/settings.py

Add overwrite = False to default settings. Overwrite is set to True in compute.base when resuming a service. In order to reliably use this setting in apps, it needs to have a default value.

Default overwrite setting

---

terra/compute/docker.py
terra/compute/singularity.py

Add default `compose_files` for docker and singularity services, should expected file exist.
- Default docker service `compose_file` is `$TERRA_APP_DIR/docker-compose.yml`
- Default singularity service `compose_file` is `$TERRA_APP_DIR/singular-compose.env`
Users may still override these default files as they see fit.

default compose_files

---

terra.env
terra/compute/base.py
terra/compute/container.py

Define the default container service `compose_service_name` as `${TERRA_APP_PREFIXES[0]}_COMPOSE_SERVICE_RUNNER` (as long as that environment variable exists).  This additionally adds the `_env_array` function to the base service, allowing services to more easily recover python compatible arrays from bash arrays encoded with `array_to_python_ast_list_of_strings`.

default compose_service_name 

---

Justfile
Pipfile
Pipfile.lock
freeze/hook-celery.py
freeze/terra.spec
setup.py
terra.env
terra/logger.py
terra/tests/test_core_settings.py

- Fixed bad RODEO paths in redis secret filenames
- Added `VIRTUALENV_PIP` to `terra.env` so that apps do not need to be responsible for this (Can be commented out in the future, due to the removal of `envcontext`)
- Removed `envcontext` and use a vendored version in VSI common instead. The `envcontext` `setup.py` file is bad, and has bad metadata that now causes it to fail to install correctly.
- Replaces the old makeself calls with the new improved makeself calls. Creates a more reliable frozen app
- Fixed how warnings are set up, so that previous warning filters are no longer wiped by accident. Previous, `terra.logging` had to be imported before setting up filters, this will no longer be true
- Celery workers were not working in a pyinstaller app due to hidden imports, this should be …

Pyinstaller celery

---

terra/compute/base.py
terra/core/settings.py
terra/executor/celery/executor.py
terra/logger.py
terra/tests/test_logger.py

add `settings.logging.log_file` to define log file location, defaulting to `<processing_dir>/terra_log`.  Allows users to easily control & discover log file location.  Note whenever the log file is initialized, we ensure the directory containing the log file exists.

settings.logging.log_file

---

terra/tests/test_core_settings.py

default `settings.processing_dir` could be in two places, depending on writability of `os.getcwd()`.  Test both scenarios.

test processing_dir default

---

.circleci/config.yml

circleci - fix deploy_docs for `cimg/python`, attaching persisted workspace at `/tmp/docs` (rather than `/docs`)

circleci deploy_docs

---

terra/logger.py

new logger convenience functions:
- `_checkLevel` to return integer log level from settings, useful for log level comparison
- `_disableDebug` to disable debug logging for selected packages based on the settings log level, enabling spam log messages from other packages only at `DEBUG4`

_checkLevel and _disableDebug

---

Justfile
terra.env
terra/executor/celery/__main__.py
terra/executor/celery/celeryconfig.py
terra/task.py
terra/tests/test_executor_celery.py

`just terra celery` to run a terra celery worker.  `TERRA_CELERY_*` environment variables are now intended to configure the _terra_ celery worker (not celery workers for terra apps).  The celery queue and included modules are configured from the command line.
Terra apps are expected to provide their own environment variables (e.g., `TERRA_DSM_CELERY_*) and configure their own queues and included modules from the command line.
The new generic task `terra.task.subprocess` (in the celery queue `terra`) will allow celery to execute a shell command via `subprocess.run`.  Note this task will be run with the terra pipenv/virtualenv disabled.

just terra celery

---

Justfile
Pipfile
Pipfile.lock
docker-compose-main.yml
docker/redis.Dockerfile
docker/redis.Justfile
docker/terra.Dockerfile
docker/tosingular
docs/conf.py
setup.py
singular-compose.env
terra.env
terra/compute/base.py
terra/compute/container.py
terra/compute/docker.py
terra/compute/singularity.py
terra/core/settings.py
terra/executor/celery/__init__.py
terra/executor/celery/__main__.py
terra/executor/celery/celeryconfig.py
terra/executor/celery/executor.py
terra/executor/process.py
terra/executor/resources.py
terra/tests/test_compute_docker.py

Changes:
- Use resources class that uses file locking to sync resources across multiple processes, but not across multiple machines. The goal of this was to manage the number of worker that can use individual pieces of harder, e.g. 4 workers per GPU
- We were using `terra.executor.celery` as a CLI in leu of the `celery` executable script
- This created too many problems that started to explode once I started using `celery multi`. Instead, we are back to using the original `celery` executable, the way it was intended
- We are able to accomplish the same changes using signals in the "celery app" `terra.executor.celery.app`
- Added `just terra celery-status` to list the number of celery workers currently connected
- Added `just terra redis-monitor` to literally dump every redis message to …

Andy 20210504

---

terra/executor/resources.py

- Hardlocks in windows are sensitive to the file pointer
Apparently, locks in windows lock specific bytes in a file, not a file as a whole.
https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/locking?view=msvc-170

Only write to soft locks

---

Pipfile.lock

update celery to 5.2.2 due to vulnerability https://github.com/advisories/GHSA-q4xr-rc97-m4xx

celery 5.2.2

---

terra/utils/cli.py

`ArgumentParser::add_settings_file` to add positional argument for settings file. 
- special case if `TERRA_SETTINGS_FILE` is already defined, using `TERRA_SETTINGS_FILE` as the default value. Users may still enter an alternative settings file at the command line if desired.
- users may also override `add_argument` kwargs, for example changing the help statement.

ArgumentParser::add_settings_file

---

terra/compute/singularity.py
terra/tests/test_compute_singularity.py

inject `TERRA_SETTINGS_FILE` into singularity environment using `SINGULARITYENV_*`
https://docs.sylabs.io/guides/3.7/user-guide/environment_and_metadata.html#environment-overview
We favor the `SINGULARITYENV_` method for compatibility with `just singular-compose` which currently requires the argument after `run` to be the service name.
Follow up to PR #134

singularity TERRA_SETTINGS_FILE 

---

Justfile

Disable terra logging magic during pyinstaller via `TERRA_UNITTEST=1`

terra pyinstaller logging

---

Justfile
terra.env

Setting up pipenv on terra has been plagued with many corner cases of failure for a while. It always gets fixed by hand, and the problem is never really solved.
This is the first attempt to fix it. If `pipenv` is not detected, then it will automatically:
1. Download miniconda
2. Use miniconda to download python 3.8.16
3. Use python 3.8.16 to install pipenv 2023.4.29 and virtualenv 20.23.0
4. Use pipenv 2023.4.29 to create a python 3.8.16 virtualenv and sync to it
This should resolve most of the issue we are constantly running into

Terra pipenv setup

---

terra/tests/test_utils_path.py
terra/utils/path.py

Update the function `utils.path.patch_volume` which translates a path value according to a volume_map. The function previously selected the first volume_map item that matches the value to translated, which means the order of the volume_map is important for successful translation. This change selects the "best" volume_map item, where "best" is defined as the volume_map item most similar to the value to be translated with the smallest remainder.
Expand the `patch_volume` tests to add volume_map items with similar prefixes, and also test a reversed volume_map to ensure volume_map order is no longer important.

best patch_volume

---

terra/core/settings.py
terra/tests/test_core_settings.py
terra/tests/test_utils_cli.py
terra/utils/cli.py

Adds the feature that an empty settings file is parsed like a normal empty dictionary. There are a number of reasons why this feature is useful, e.g. I don't want to create an empty json file and just want to pass in `/dev/null`/`Nul`.
Instead of hard coding `/dev/null` and `Nul`, it just allows any empty file to be parsed as `{}`.
---
I looked into changing the default value of the settings file parser to use to dev null, however the current behavior of `add_settings_file` to the argument parser already handles this by setting the settings file to required _unless_ `TERRA_SETTINGS_FILE` is set, in which case it become optional. So I decided not to unexpectedly change this behavior for all Terra projects. If this is a desired feature, we can add a parameter to `add_settings_file` to …

Add ability to use an empty config file

---

terra/compute/base.py
terra/compute/docker.py
terra/compute/singularity.py
terra/compute/virtualenv.py
terra/tests/test_compute_docker.py
terra/tests/test_compute_singularity.py
terra/tests/test_compute_virtualenv.py

Instead of having the ServiceRunFailed message tell you nothing, it at least tells you the exit code throw by the child process, and tries to decode it if it's above 127

Initial ServiceRunFailed update

---

terra/compute/docker.py
terra/tests/test_compute_docker.py

`yaml.load` -> `yaml.safe_load` 
https://security.openstack.org/guidelines/dg_avoid-dangerous-input-parsing-libraries.html

yaml.safe_load

---

Justfile

if pipenv exists on the PATH it will be found; but we want to find the version terra installs

find the right pipenv

---

Justfile

PR #200 forces the command `pipenv` to be located at `${TERRA_CWD}/build/pipenv/bin/pipenv` by default.  Users can override this location by setting `PIPENV_EXE`, but this override is not automatically created for users that place the terra python/pipenv in a non-default location.
For example, running `just terra setup --download --dir ./foo` places `pipenv` at `${TERRA_CWD}/foo/bin/pipenv`.  Users must then manually define `PIPENV_EXE` to ensure terra can discover the command location.
This PR adds the `PIPENV_EXE` environment variable to the terra `local.env` file during `just terra setup` so users need not define the variable themselves.

PIPENV_EXE

---

.troubleshoot.d/terra_installed
Justfile
terra/compute/base.py
terra/compute/container.py
terra/core/exceptions.py
terra/core/settings.py
terra/logger.py
terra/tests/test_compute_docker.py
terra/tests/test_compute_singularity.py
terra/tests/test_compute_virtualenv.py
terra/tests/test_logger.py

- Updating VSI Common to include new troubleshoot
- Service runners errors now have a more succinct stack trace
- No extra terra stack trace. This adds no additional information
- No additional just stack trace. This adds no additional information
- Service Runner uncaught exception result in an exit 62 instead exit 1..
- A "Report" is printed out at the end of a terra run.
- Currently this means the last N (`settings.logging.severe_buffer_length`, default: 20) messages of severity (`settings.logging.severe_level` default: Error) are printed out again when a terra run concludes.

Terra cleanup and troubleshoot

---

terra/core/settings.py

Adds a `to_dict` function to properly convert to a python `dict` with all terra expansion applied.
Allows you to fix the bug when `~` is not expanded when a leaf of settings is passed to a function

Add to_dict to fix expansion issue

---

terra/executor/sync.py
terra/executor/thread.py
terra/utils/cli.py

The fix in #151 introduced a new behavior, where debugging tasks using dbstop no longer included any stack frames, meaning none of the variables could be checked.
This was done to stop many exceptions from consuming large amounts of memory, especially when some tasks throwing exceptions were ok.
So now, when the dbstop flags, this memory leak prevention code is disabled.

Fix stack frames being cleared when using a debugger

---

setup.py
terra/executor/resources.py
terra/tests/test_executor_resources.py

Remove `filelock` package version constraint.  `filelock<3.12` uses a `_lock_counter` property, while later packages use a `lock_counter` property (without the leading underscore).  Here, we check for the existence of both properties. Related to the previously closed PR #152.

remove filelock constraint

---

Justfile

In the `Justfile::Terra_Pipenv` function, add `TERRA_PIPENV_PIPFILE` to allow for custom pipfile.  This supports the use case where terra is installed as a part of another pipenv and an isolated terra pipenv is not available.  Default `TERRA_PIPENV_PIPFILE` is unchanged at the `${TERRA_CWD}/Pipfile}` location.

TERRA_PIPENV_PIPFILE

---

Justfile
terra.env

Terra apps will no longer use an artificial prefix (e.g. TERRA_XYZ_...), but TERRA_... prefix directly (e.g. TERRA_CWD). So now for pure terra variables, they will be TERRA_TERRA_.... This pattern will allow for terra justfile-plugin to more easily work with any terra app, especially with the multi app work coming up.

Fix issues when terra apps use TERRA_CWD

---

terra/compute/base.py
terra/tests/test_compute_base.py

This PR adds `create_service_dir`, which was originally in `file_utils.py`, to `compute.base.py`, since it is Terra-related.

Add create_service_dir to compute base.py

---

docs/terra/settings.rst
terra/compute/base.py
terra/core/settings.py
terra/logger.py

The first step to setting up file sockets, so that logging will work in WSL and we don't have to use an actual IP/port for basic logging. (For distributed computers (i.e. celery) we will always need to use IP and port).

Make a combined address for terra logging

---

terra/compute/base.py
terra/compute/container.py
terra/core/settings.py
terra/logger.py
terra/tests/test_compute_base.py
terra/tests/test_compute_container.py
terra/tests/test_utils_path.py
terra/utils/path.py

Terra components (controller, runners, and task runners) use a BSD socket to communicate IPC using TCP.
This has been functioning using the standard IP network, but there have been issues with this over time:
1. Port in use. This has been fix by using port 0 to auto assign an port, but was historically a problem.
2. Firewall and IP routing can be a problem in some setups. Especially Windows using WSL. Sometimes it works when you use the right IP, and sometimes it doesn't.
3. Distributed computing needs a firewall to allow the communication.
With the file based socket, the first 2 issues are completely resolves. When running on a windows host, you will still need to use an IP socket, but that shouldn't be a problem, as there are not container networks to contend with.
The 3rd issue will …

File socket for terra logging
