VisionSystemsInc/terra

- Pipfile
- Pipfile.lock
- terra.env
- terra/compute/docker.py
Update for docker in windows
- replace set_temp_array with set_array_default
- add pypiwin32 to pipenv
- terra services should apply docker translation only if setting value is string
- update vsi_common for latest changes
> docker with windows

- terra/compute/base.py
- terra/compute/container.py
- terra/compute/virtualenv.py
Keep a consistent add_volume signature across all services. Docker compute now checks if the volume is None.
> add_volume consistency

- Justfile
- docker/terra.Dockerfile
Minor updates in sync targets, and update vsi_common
> Singularity 2.6 fun

- terra/logger.py
> Make logging python 3.8 compatible

- Justfile
- terra/compute/docker.py
Signed-off-by: Andy Neff <andy@visionsystemsinc.com>
> Add specifying justfile to docker compute

- docker-compose.yml
Remove `cache_from` in `docker-compose.yml`
> remove cache_from in docker-compose.yml

- docs/terra/settings.rst
- terra/workflow.py
Formalize generic PipelineWorkflow
> Added PipelineWorkflow

- terra/task.py
Signed-off-by: Andy Neff <andy@visionsystemsinc.com>
> Fix resetting zone on exception [skipci]

- Justfile
- terra/executor/celery/__init__.py
- terra/executor/celery/__main__.py
- terra/executor/dummy.py
create a simple __main__.py to start the celery customization
> create a simple __main__.py

- terra.env
- terra/compute/base.py
- terra/core/settings.py
- terra/executor/celery/executor.py
- terra/executor/thread.py
- terra/executor/utils.py
- terra/logger.py
- terra/tests/test_executor_utils.py
Mitigate the new issues with ThreadPoolExecutor
> Multithread safe settings

- terra/compute/docker.py
docker `volume_map` do not check for `startswith('/')`, instead check for docker volume regex.
> docker volume_map

- terra/compute/utils.py
- terra/tests/test_compute_utils.py
Fix the problem with environment variables and ~ in setting filenames
> Fix patch_volume

- Justfile
- Update vsi_common, now including new just_install_functions
- Make just_install_functions available in terra Justfile
> just_install

- .gitmodules
Make vsi_common submodule relative
> vsi_common relative submodule

- .circleci/config.yml
switch circleci to `cimg/python` (provided by circleci)
> circleci cimg/python

- terra/tests/test_utils_workflow.py
- terra/utils/workflow.py
Refactor status.json to contain a dictionary of stage status information.  Update resumable tests given new status.json format.
Consider a pipeline containing the stages `["A", "B", "C"]`.  A status.json of the form
```
{
"A": {"name", "A", "state", "done"},
"B": {"name", "B", "state", "starting"},
}
```
indicates stage `A` is complete and stage `B` is starting.
A stage is injected with the status subdict for that stage. For example, the `self` object for stage `B` would contain 
```
self.status == {"name": "B", "state": "starting"}
```
> status dict

- Justfile
Signed-off-by: Andy Neff <andy@visionsystemsinc.com>
> Update vsicommon, and make ask_question default answers work

- terra/logger.py
Just some side changes, I don't care when these get merged into other apps. No rush there
> Hide 3rd party logs the right way

- Justfile
- Pipfile
- Pipfile.lock
- setup.py
Move flower to a dev package. It's only used as a debugging tool, after all.
> Move flower to a dev package

- terra/task.py
Update terra.task.subprocess to ingest settings.
- make use of an input settings dictionary if provided with the task request.  Settings are saved to a temporary file, then provided to the subprocess via the `TERRA_SETTINGS_FILE` env var.
- Additionally use `original_shared_task` for `terra.task.subprocess` as this is not a `TerraTask` in the traditional sense.
> terra.task.subprocess 

- Justfile
- terra/compute/container.py
- terra/compute/utils.py
- terra/task.py
- terra/tests/test_compute_utils.py
- terra/tests/test_utils_path.py
- terra/utils/cli.py
- terra/utils/new.py
- terra/utils/path.py
Move all the path translation related code into one centralized location: `terra.utils.path`
> Path refactor

- terra/core/settings.py
- terra/tests/test_core_settings.py
- terra/tests/test_core_utils.py
- terra/tests/test_executor_resources.py
Update vsi_common.  Additional minor update to pass pep8.
> vsi_common

- Pipfile.lock
- `pipenv lock` for latest dependencies
- update vsi_common to latest
> pipenv lock & vsi_common

- docs/conf.py
update vsi_common, which updates sphinx build environment to python 3.10.11
> vsi_common sphinx

- .circleci/config.yml
Update master branch name to "main"
> Update master branch name to main

- Pipfile.lock
minor Pipfile updates for `filelock` & `redis` to support customer security
> minor versions

- terra/tests/test_utils_logger.py
- terra/utils/logger.py
Added common code to easily log commit version in terra logs.
> Add commit logger util

- terra/compute/docker.py
Starting a service involves a lot of moving parts. While it's possible to replicate many of these parts from the logs files, it is ultimately cumbersome and is out of reach of most users.
Introduces:
- TERRA_DEBUG_SERVICE (can match anywhere in class heirarchy)
- TERRA_DEBUG_SHELL (posix form)
> Debug feature to debug the exact environment of a service

- terra/executor/resources.py
ResourceManager allowing directory to not exist to handle race condition.
> Race Conditions

- terra/logger.py
There is no `AF_UNIX` on windows, it's not even enumerated
> windows compatibility fix
